// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Paper.proto

package com.fudan.ast.grpc.lib;

public interface AddPaperToSessionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddPaperToSessionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
