// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Paper.proto

package com.fudan.ast.grpc.lib;

public interface AvailablePapersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AvailablePapersResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Paper papers = 1;</code>
   */
  java.util.List<com.fudan.ast.grpc.lib.Paper> 
      getPapersList();
  /**
   * <code>repeated .Paper papers = 1;</code>
   */
  com.fudan.ast.grpc.lib.Paper getPapers(int index);
  /**
   * <code>repeated .Paper papers = 1;</code>
   */
  int getPapersCount();
  /**
   * <code>repeated .Paper papers = 1;</code>
   */
  java.util.List<? extends com.fudan.ast.grpc.lib.PaperOrBuilder> 
      getPapersOrBuilderList();
  /**
   * <code>repeated .Paper papers = 1;</code>
   */
  com.fudan.ast.grpc.lib.PaperOrBuilder getPapersOrBuilder(
      int index);
}
