// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Submission.proto

package com.fudan.ast.grpc.lib;

public interface CreateSubmissionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateSubmissionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
