// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Submission.proto

package com.fudan.ast.grpc.lib;

//import jdk.internal.org.objectweb.asm.ClassWriter;

/**
 * Protobuf type {@code CreateSubmissionRequest}
 */
public  final class CreateSubmissionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreateSubmissionRequest)
    CreateSubmissionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateSubmissionRequest.newBuilder() to construct.
  private CreateSubmissionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateSubmissionRequest() {
    conferenceId_ = 0;
    title_ = "";
    abstract_ = "";
    submitterId_ = 0;
    paperFilePath_ = "";
    status_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateSubmissionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 16: {

            conferenceId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            abstract_ = s;
            break;
          }
          case 40: {

            submitterId_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            paperFilePath_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fudan.ast.grpc.lib.SubmissionProto.internal_static_CreateSubmissionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fudan.ast.grpc.lib.SubmissionProto.internal_static_CreateSubmissionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fudan.ast.grpc.lib.CreateSubmissionRequest.class, com.fudan.ast.grpc.lib.CreateSubmissionRequest.Builder.class);
  }

  public static final int CONFERENCE_ID_FIELD_NUMBER = 2;
  private int conferenceId_;
  /**
   * <code>int32 conference_id = 2;</code>
   */
  public int getConferenceId() {
    return conferenceId_;
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 3;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ABSTRACT_FIELD_NUMBER = 4;
  private volatile java.lang.Object abstract_;
  /**
   * <code>string abstract = 4;</code>
   */
  public java.lang.String getAbstract() {
    java.lang.Object ref = abstract_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      abstract_ = s;
      return s;
    }
  }
  /**
   * <code>string abstract = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAbstractBytes() {
    java.lang.Object ref = abstract_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      abstract_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBMITTER_ID_FIELD_NUMBER = 5;
  private int submitterId_;
  /**
   * <code>int32 submitter_id = 5;</code>
   */
  public int getSubmitterId() {
    return submitterId_;
  }

  public static final int PAPER_FILE_PATH_FIELD_NUMBER = 6;
  private volatile java.lang.Object paperFilePath_;
  /**
   * <code>string paper_file_path = 6;</code>
   */
  public java.lang.String getPaperFilePath() {
    java.lang.Object ref = paperFilePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paperFilePath_ = s;
      return s;
    }
  }
  /**
   * <code>string paper_file_path = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPaperFilePathBytes() {
    java.lang.Object ref = paperFilePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paperFilePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 7;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 7;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (conferenceId_ != 0) {
      output.writeInt32(2, conferenceId_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (!getAbstractBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, abstract_);
    }
    if (submitterId_ != 0) {
      output.writeInt32(5, submitterId_);
    }
    if (!getPaperFilePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, paperFilePath_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (conferenceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, conferenceId_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (!getAbstractBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, abstract_);
    }
    if (submitterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, submitterId_);
    }
    if (!getPaperFilePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, paperFilePath_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fudan.ast.grpc.lib.CreateSubmissionRequest)) {
      return super.equals(obj);
    }
    com.fudan.ast.grpc.lib.CreateSubmissionRequest other = (com.fudan.ast.grpc.lib.CreateSubmissionRequest) obj;

    boolean result = true;
    result = result && (getConferenceId()
        == other.getConferenceId());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getAbstract()
        .equals(other.getAbstract());
    result = result && (getSubmitterId()
        == other.getSubmitterId());
    result = result && getPaperFilePath()
        .equals(other.getPaperFilePath());
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONFERENCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConferenceId();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + ABSTRACT_FIELD_NUMBER;
    hash = (53 * hash) + getAbstract().hashCode();
    hash = (37 * hash) + SUBMITTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSubmitterId();
    hash = (37 * hash) + PAPER_FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPaperFilePath().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fudan.ast.grpc.lib.CreateSubmissionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }


    /**
   * Protobuf type {@code CreateSubmissionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateSubmissionRequest)
      com.fudan.ast.grpc.lib.CreateSubmissionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fudan.ast.grpc.lib.SubmissionProto.internal_static_CreateSubmissionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fudan.ast.grpc.lib.SubmissionProto.internal_static_CreateSubmissionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fudan.ast.grpc.lib.CreateSubmissionRequest.class, com.fudan.ast.grpc.lib.CreateSubmissionRequest.Builder.class);
    }

    // Construct using com.fudan.ast.grpc.lib.CreateSubmissionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      conferenceId_ = 0;

      title_ = "";

      abstract_ = "";

      submitterId_ = 0;

      paperFilePath_ = "";

      status_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fudan.ast.grpc.lib.SubmissionProto.internal_static_CreateSubmissionRequest_descriptor;
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.CreateSubmissionRequest getDefaultInstanceForType() {
      return com.fudan.ast.grpc.lib.CreateSubmissionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.CreateSubmissionRequest build() {
      com.fudan.ast.grpc.lib.CreateSubmissionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.CreateSubmissionRequest buildPartial() {
      com.fudan.ast.grpc.lib.CreateSubmissionRequest result = new com.fudan.ast.grpc.lib.CreateSubmissionRequest(this);
      result.conferenceId_ = conferenceId_;
      result.title_ = title_;
      result.abstract_ = abstract_;
      result.submitterId_ = submitterId_;
      result.paperFilePath_ = paperFilePath_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fudan.ast.grpc.lib.CreateSubmissionRequest) {
        return mergeFrom((com.fudan.ast.grpc.lib.CreateSubmissionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fudan.ast.grpc.lib.CreateSubmissionRequest other) {
      if (other == com.fudan.ast.grpc.lib.CreateSubmissionRequest.getDefaultInstance()) return this;
      if (other.getConferenceId() != 0) {
        setConferenceId(other.getConferenceId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getAbstract().isEmpty()) {
        abstract_ = other.abstract_;
        onChanged();
      }
      if (other.getSubmitterId() != 0) {
        setSubmitterId(other.getSubmitterId());
      }
      if (!other.getPaperFilePath().isEmpty()) {
        paperFilePath_ = other.paperFilePath_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fudan.ast.grpc.lib.CreateSubmissionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fudan.ast.grpc.lib.CreateSubmissionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int conferenceId_ ;
    /**
     * <code>int32 conference_id = 2;</code>
     */
    public int getConferenceId() {
      return conferenceId_;
    }
    /**
     * <code>int32 conference_id = 2;</code>
     */
    public Builder setConferenceId(int value) {
      
      conferenceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 conference_id = 2;</code>
     */
    public Builder clearConferenceId() {
      
      conferenceId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object abstract_ = "";
    /**
     * <code>string abstract = 4;</code>
     */
    public java.lang.String getAbstract() {
      java.lang.Object ref = abstract_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        abstract_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string abstract = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAbstractBytes() {
      java.lang.Object ref = abstract_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        abstract_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string abstract = 4;</code>
     */
    public Builder setAbstract(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      abstract_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string abstract = 4;</code>
     */
    public Builder clearAbstract() {
      
      abstract_ = getDefaultInstance().getAbstract();
      onChanged();
      return this;
    }
    /**
     * <code>string abstract = 4;</code>
     */
    public Builder setAbstractBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      abstract_ = value;
      onChanged();
      return this;
    }

    private int submitterId_ ;
    /**
     * <code>int32 submitter_id = 5;</code>
     */
    public int getSubmitterId() {
      return submitterId_;
    }
    /**
     * <code>int32 submitter_id = 5;</code>
     */
    public Builder setSubmitterId(int value) {
      
      submitterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 submitter_id = 5;</code>
     */
    public Builder clearSubmitterId() {
      
      submitterId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object paperFilePath_ = "";
    /**
     * <code>string paper_file_path = 6;</code>
     */
    public java.lang.String getPaperFilePath() {
      java.lang.Object ref = paperFilePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paperFilePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string paper_file_path = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPaperFilePathBytes() {
      java.lang.Object ref = paperFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paperFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string paper_file_path = 6;</code>
     */
    public Builder setPaperFilePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paperFilePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string paper_file_path = 6;</code>
     */
    public Builder clearPaperFilePath() {
      
      paperFilePath_ = getDefaultInstance().getPaperFilePath();
      onChanged();
      return this;
    }
    /**
     * <code>string paper_file_path = 6;</code>
     */
    public Builder setPaperFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      paperFilePath_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 7;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 7;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 7;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 7;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreateSubmissionRequest)
  }

  // @@protoc_insertion_point(class_scope:CreateSubmissionRequest)
  private static final com.fudan.ast.grpc.lib.CreateSubmissionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fudan.ast.grpc.lib.CreateSubmissionRequest();
  }

  public static com.fudan.ast.grpc.lib.CreateSubmissionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateSubmissionRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateSubmissionRequest>() {
    @java.lang.Override
    public CreateSubmissionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateSubmissionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateSubmissionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateSubmissionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fudan.ast.grpc.lib.CreateSubmissionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

