// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Submission.proto

package com.fudan.ast.grpc.lib;

public interface CreateSubmissionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateSubmissionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 conference_id = 2;</code>
   */
  int getConferenceId();

  /**
   * <code>string title = 3;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string abstract = 4;</code>
   */
  java.lang.String getAbstract();
  /**
   * <code>string abstract = 4;</code>
   */
  com.google.protobuf.ByteString
      getAbstractBytes();

  /**
   * <code>int32 submitter_id = 5;</code>
   */
  int getSubmitterId();

  /**
   * <code>string paper_file_path = 6;</code>
   */
  java.lang.String getPaperFilePath();
  /**
   * <code>string paper_file_path = 6;</code>
   */
  com.google.protobuf.ByteString
      getPaperFilePathBytes();

  /**
   * <code>string status = 7;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 7;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
