// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Paper.proto

package com.fudan.ast.grpc.lib;

public interface DeletePaperFromSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeletePaperFromSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string submitter_id = 1;</code>
   */
  java.lang.String getSubmitterId();
  /**
   * <code>string submitter_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSubmitterIdBytes();
}
