// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.fudan.ast.grpc.lib;

public interface JwtTokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JwtToken)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jwtToken = 1;</code>
   */
  java.lang.String getJwtToken();
  /**
   * <code>string jwtToken = 1;</code>
   */
  com.google.protobuf.ByteString
      getJwtTokenBytes();
}
