// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Paper.proto

package com.fudan.ast.grpc.lib;

/**
 * Protobuf type {@code Paper}
 */
public  final class Paper extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Paper)
    PaperOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Paper.newBuilder() to construct.
  private Paper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Paper() {
    id_ = 0;
    submitterId_ = 0;
    title_ = "";
    paperFilePath_ = "";
    commitTime_ = "";
    lastModified_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Paper(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            submitterId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            paperFilePath_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            commitTime_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            lastModified_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fudan.ast.grpc.lib.PaperProto.internal_static_Paper_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fudan.ast.grpc.lib.PaperProto.internal_static_Paper_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fudan.ast.grpc.lib.Paper.class, com.fudan.ast.grpc.lib.Paper.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int SUBMITTER_ID_FIELD_NUMBER = 2;
  private int submitterId_;
  /**
   * <code>int32 submitter_id = 2;</code>
   */
  public int getSubmitterId() {
    return submitterId_;
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 3;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAPER_FILE_PATH_FIELD_NUMBER = 4;
  private volatile java.lang.Object paperFilePath_;
  /**
   * <code>string paper_file_path = 4;</code>
   */
  public java.lang.String getPaperFilePath() {
    java.lang.Object ref = paperFilePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paperFilePath_ = s;
      return s;
    }
  }
  /**
   * <code>string paper_file_path = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPaperFilePathBytes() {
    java.lang.Object ref = paperFilePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paperFilePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMIT_TIME_FIELD_NUMBER = 5;
  private volatile java.lang.Object commitTime_;
  /**
   * <code>string commit_time = 5;</code>
   */
  public java.lang.String getCommitTime() {
    java.lang.Object ref = commitTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commitTime_ = s;
      return s;
    }
  }
  /**
   * <code>string commit_time = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCommitTimeBytes() {
    java.lang.Object ref = commitTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commitTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_MODIFIED_FIELD_NUMBER = 6;
  private volatile java.lang.Object lastModified_;
  /**
   * <code>string last_modified = 6;</code>
   */
  public java.lang.String getLastModified() {
    java.lang.Object ref = lastModified_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastModified_ = s;
      return s;
    }
  }
  /**
   * <code>string last_modified = 6;</code>
   */
  public com.google.protobuf.ByteString
      getLastModifiedBytes() {
    java.lang.Object ref = lastModified_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastModified_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (submitterId_ != 0) {
      output.writeInt32(2, submitterId_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (!getPaperFilePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, paperFilePath_);
    }
    if (!getCommitTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, commitTime_);
    }
    if (!getLastModifiedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, lastModified_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (submitterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, submitterId_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (!getPaperFilePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, paperFilePath_);
    }
    if (!getCommitTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, commitTime_);
    }
    if (!getLastModifiedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, lastModified_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fudan.ast.grpc.lib.Paper)) {
      return super.equals(obj);
    }
    com.fudan.ast.grpc.lib.Paper other = (com.fudan.ast.grpc.lib.Paper) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getSubmitterId()
        == other.getSubmitterId());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getPaperFilePath()
        .equals(other.getPaperFilePath());
    result = result && getCommitTime()
        .equals(other.getCommitTime());
    result = result && getLastModified()
        .equals(other.getLastModified());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + SUBMITTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSubmitterId();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + PAPER_FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPaperFilePath().hashCode();
    hash = (37 * hash) + COMMIT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getCommitTime().hashCode();
    hash = (37 * hash) + LAST_MODIFIED_FIELD_NUMBER;
    hash = (53 * hash) + getLastModified().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fudan.ast.grpc.lib.Paper parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Paper parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.Paper parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.Paper parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fudan.ast.grpc.lib.Paper prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Paper}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Paper)
      com.fudan.ast.grpc.lib.PaperOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fudan.ast.grpc.lib.PaperProto.internal_static_Paper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fudan.ast.grpc.lib.PaperProto.internal_static_Paper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fudan.ast.grpc.lib.Paper.class, com.fudan.ast.grpc.lib.Paper.Builder.class);
    }

    // Construct using com.fudan.ast.grpc.lib.Paper.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      submitterId_ = 0;

      title_ = "";

      paperFilePath_ = "";

      commitTime_ = "";

      lastModified_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fudan.ast.grpc.lib.PaperProto.internal_static_Paper_descriptor;
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.Paper getDefaultInstanceForType() {
      return com.fudan.ast.grpc.lib.Paper.getDefaultInstance();
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.Paper build() {
      com.fudan.ast.grpc.lib.Paper result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.Paper buildPartial() {
      com.fudan.ast.grpc.lib.Paper result = new com.fudan.ast.grpc.lib.Paper(this);
      result.id_ = id_;
      result.submitterId_ = submitterId_;
      result.title_ = title_;
      result.paperFilePath_ = paperFilePath_;
      result.commitTime_ = commitTime_;
      result.lastModified_ = lastModified_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fudan.ast.grpc.lib.Paper) {
        return mergeFrom((com.fudan.ast.grpc.lib.Paper)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fudan.ast.grpc.lib.Paper other) {
      if (other == com.fudan.ast.grpc.lib.Paper.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getSubmitterId() != 0) {
        setSubmitterId(other.getSubmitterId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getPaperFilePath().isEmpty()) {
        paperFilePath_ = other.paperFilePath_;
        onChanged();
      }
      if (!other.getCommitTime().isEmpty()) {
        commitTime_ = other.commitTime_;
        onChanged();
      }
      if (!other.getLastModified().isEmpty()) {
        lastModified_ = other.lastModified_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fudan.ast.grpc.lib.Paper parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fudan.ast.grpc.lib.Paper) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int submitterId_ ;
    /**
     * <code>int32 submitter_id = 2;</code>
     */
    public int getSubmitterId() {
      return submitterId_;
    }
    /**
     * <code>int32 submitter_id = 2;</code>
     */
    public Builder setSubmitterId(int value) {
      
      submitterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 submitter_id = 2;</code>
     */
    public Builder clearSubmitterId() {
      
      submitterId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object paperFilePath_ = "";
    /**
     * <code>string paper_file_path = 4;</code>
     */
    public java.lang.String getPaperFilePath() {
      java.lang.Object ref = paperFilePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paperFilePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string paper_file_path = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPaperFilePathBytes() {
      java.lang.Object ref = paperFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paperFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string paper_file_path = 4;</code>
     */
    public Builder setPaperFilePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paperFilePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string paper_file_path = 4;</code>
     */
    public Builder clearPaperFilePath() {
      
      paperFilePath_ = getDefaultInstance().getPaperFilePath();
      onChanged();
      return this;
    }
    /**
     * <code>string paper_file_path = 4;</code>
     */
    public Builder setPaperFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      paperFilePath_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object commitTime_ = "";
    /**
     * <code>string commit_time = 5;</code>
     */
    public java.lang.String getCommitTime() {
      java.lang.Object ref = commitTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commitTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string commit_time = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCommitTimeBytes() {
      java.lang.Object ref = commitTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commitTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commit_time = 5;</code>
     */
    public Builder setCommitTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      commitTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string commit_time = 5;</code>
     */
    public Builder clearCommitTime() {
      
      commitTime_ = getDefaultInstance().getCommitTime();
      onChanged();
      return this;
    }
    /**
     * <code>string commit_time = 5;</code>
     */
    public Builder setCommitTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      commitTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastModified_ = "";
    /**
     * <code>string last_modified = 6;</code>
     */
    public java.lang.String getLastModified() {
      java.lang.Object ref = lastModified_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastModified_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string last_modified = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLastModifiedBytes() {
      java.lang.Object ref = lastModified_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastModified_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string last_modified = 6;</code>
     */
    public Builder setLastModified(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastModified_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string last_modified = 6;</code>
     */
    public Builder clearLastModified() {
      
      lastModified_ = getDefaultInstance().getLastModified();
      onChanged();
      return this;
    }
    /**
     * <code>string last_modified = 6;</code>
     */
    public Builder setLastModifiedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastModified_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Paper)
  }

  // @@protoc_insertion_point(class_scope:Paper)
  private static final com.fudan.ast.grpc.lib.Paper DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fudan.ast.grpc.lib.Paper();
  }

  public static com.fudan.ast.grpc.lib.Paper getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Paper>
      PARSER = new com.google.protobuf.AbstractParser<Paper>() {
    @java.lang.Override
    public Paper parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Paper(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Paper> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Paper> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fudan.ast.grpc.lib.Paper getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

