// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Paper.proto

package com.fudan.ast.grpc.lib;

public interface PaperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Paper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 submitter_id = 2;</code>
   */
  int getSubmitterId();

  /**
   * <code>string title = 3;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string paper_file_path = 4;</code>
   */
  java.lang.String getPaperFilePath();
  /**
   * <code>string paper_file_path = 4;</code>
   */
  com.google.protobuf.ByteString
      getPaperFilePathBytes();

  /**
   * <code>string commit_time = 5;</code>
   */
  java.lang.String getCommitTime();
  /**
   * <code>string commit_time = 5;</code>
   */
  com.google.protobuf.ByteString
      getCommitTimeBytes();

  /**
   * <code>string last_modified = 6;</code>
   */
  java.lang.String getLastModified();
  /**
   * <code>string last_modified = 6;</code>
   */
  com.google.protobuf.ByteString
      getLastModifiedBytes();
}
