// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.fudan.ast.grpc.lib;

public interface RegisterUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegisterUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>bool state = 2;</code>
   */
  boolean getState();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
