// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Submission.proto

package com.fudan.ast.grpc.lib;

public final class SubmissionProto {
  private SubmissionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateSubmissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateSubmissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateSubmissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateSubmissionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Submission.proto\"\220\001\n\027CreateSubmissionR" +
      "equest\022\025\n\rconference_id\030\002 \001(\005\022\r\n\005title\030\003" +
      " \001(\t\022\020\n\010abstract\030\004 \001(\t\022\024\n\014submitter_id\030\005" +
      " \001(\005\022\027\n\017paper_file_path\030\006 \001(\t\022\016\n\006status\030" +
      "\007 \001(\t\"*\n\030CreateSubmissionResponse\022\016\n\006sta" +
      "tus\030\001 \001(\0102\\\n\021SubmissionService\022G\n\020Create" +
      "Submission\022\030.CreateSubmissionRequest\032\031.C" +
      "reateSubmissionResponseB+\n\026com.fudan.ast" +
      ".grpc.libB\017SubmissionProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CreateSubmissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateSubmissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateSubmissionRequest_descriptor,
        new java.lang.String[] { "ConferenceId", "Title", "Abstract", "SubmitterId", "PaperFilePath", "Status", });
    internal_static_CreateSubmissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreateSubmissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateSubmissionResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
