// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.fudan.ast.grpc.lib;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .UserInfo user = 1;</code>
   */
  java.util.List<com.fudan.ast.grpc.lib.UserInfo> 
      getUserList();
  /**
   * <code>repeated .UserInfo user = 1;</code>
   */
  com.fudan.ast.grpc.lib.UserInfo getUser(int index);
  /**
   * <code>repeated .UserInfo user = 1;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .UserInfo user = 1;</code>
   */
  java.util.List<? extends com.fudan.ast.grpc.lib.UserInfoOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .UserInfo user = 1;</code>
   */
  com.fudan.ast.grpc.lib.UserInfoOrBuilder getUserOrBuilder(
      int index);
}
