// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.fudan.ast.grpc.lib;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserByNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserByNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"(\n\024GetUserByNameRequest\022\020\n\010" +
      "username\030\001 \001(\t\"\'\n\014UserResponse\022\027\n\004user\030\001" +
      " \003(\0132\t.UserInfo\"R\n\010UserInfo\022\020\n\010username\030" +
      "\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\023\n\013affiliation\030\003 \001(" +
      "\t\022\020\n\010location\030\004 \001(\t2D\n\013UserService\0225\n\rGe" +
      "tUserByName\022\025.GetUserByNameRequest\032\r.Use" +
      "rResponseB%\n\026com.fudan.ast.grpc.libB\tUse" +
      "rProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetUserByNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetUserByNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserByNameRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfo_descriptor,
        new java.lang.String[] { "Username", "Email", "Affiliation", "Location", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
