// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conference.proto

package com.fudan.ast.grpc.lib.Conference;

public interface AddPaperRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conference.AddPaperRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 conference_id = 1;</code>
   */
  int getConferenceId();

  /**
   * <code>.conference.Paper paper = 2;</code>
   */
  boolean hasPaper();
  /**
   * <code>.conference.Paper paper = 2;</code>
   */
  com.fudan.ast.grpc.lib.Conference.Paper getPaper();
  /**
   * <code>.conference.Paper paper = 2;</code>
   */
  com.fudan.ast.grpc.lib.Conference.PaperOrBuilder getPaperOrBuilder();
}
