// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conference.proto

package com.fudan.ast.grpc.lib.Conference;

public interface ConfirmCreateConferenceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conference.ConfirmCreateConferenceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 conference_id = 1;</code>
   */
  int getConferenceId();

  /**
   * <pre>
   * 是否接受邀请
   * </pre>
   *
   * <code>bool accept = 2;</code>
   */
  boolean getAccept();
}
