// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conference.proto

package com.fudan.ast.grpc.lib.Conference;

public interface ConfirmPcMemberInvitationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conference.ConfirmPcMemberInvitationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 conference_id = 1;</code>
   */
  int getConferenceId();

  /**
   * <code>int32 user_id = 2;</code>
   */
  int getUserId();

  /**
   * <pre>
   * 是否接受邀请
   * </pre>
   *
   * <code>bool accept = 3;</code>
   */
  boolean getAccept();
}
