// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conference.proto

package com.fudan.ast.grpc.lib.Conference;

public interface InvitePcMemberRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conference.InvitePcMemberRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 conference_id = 1;</code>
   */
  int getConferenceId();

  /**
   * <code>int32 user_id = 2;</code>
   */
  int getUserId();
}
