// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conference.proto

package com.fudan.ast.grpc.lib.Conference;

public interface ListConferencesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conference.ListConferencesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page_size = 1;</code>
   */
  int getPageSize();

  /**
   * <code>int32 page_number = 2;</code>
   */
  int getPageNumber();
}
