// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conference.proto

package com.fudan.ast.grpc.lib.Conference;

/**
 * Protobuf type {@code conference.ListConferencesResponse}
 */
public  final class ListConferencesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:conference.ListConferencesResponse)
    ListConferencesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListConferencesResponse.newBuilder() to construct.
  private ListConferencesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListConferencesResponse() {
    conferences_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListConferencesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              conferences_ = new java.util.ArrayList<com.fudan.ast.grpc.lib.Conference.Conference>();
              mutable_bitField0_ |= 0x00000001;
            }
            conferences_.add(
                input.readMessage(com.fudan.ast.grpc.lib.Conference.Conference.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        conferences_ = java.util.Collections.unmodifiableList(conferences_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fudan.ast.grpc.lib.Conference.ConferenceProto.internal_static_conference_ListConferencesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fudan.ast.grpc.lib.Conference.ConferenceProto.internal_static_conference_ListConferencesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fudan.ast.grpc.lib.Conference.ListConferencesResponse.class, com.fudan.ast.grpc.lib.Conference.ListConferencesResponse.Builder.class);
  }

  public static final int CONFERENCES_FIELD_NUMBER = 1;
  private java.util.List<com.fudan.ast.grpc.lib.Conference.Conference> conferences_;
  /**
   * <code>repeated .conference.Conference conferences = 1;</code>
   */
  public java.util.List<com.fudan.ast.grpc.lib.Conference.Conference> getConferencesList() {
    return conferences_;
  }
  /**
   * <code>repeated .conference.Conference conferences = 1;</code>
   */
  public java.util.List<? extends com.fudan.ast.grpc.lib.Conference.ConferenceOrBuilder> 
      getConferencesOrBuilderList() {
    return conferences_;
  }
  /**
   * <code>repeated .conference.Conference conferences = 1;</code>
   */
  public int getConferencesCount() {
    return conferences_.size();
  }
  /**
   * <code>repeated .conference.Conference conferences = 1;</code>
   */
  public com.fudan.ast.grpc.lib.Conference.Conference getConferences(int index) {
    return conferences_.get(index);
  }
  /**
   * <code>repeated .conference.Conference conferences = 1;</code>
   */
  public com.fudan.ast.grpc.lib.Conference.ConferenceOrBuilder getConferencesOrBuilder(
      int index) {
    return conferences_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < conferences_.size(); i++) {
      output.writeMessage(1, conferences_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < conferences_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, conferences_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fudan.ast.grpc.lib.Conference.ListConferencesResponse)) {
      return super.equals(obj);
    }
    com.fudan.ast.grpc.lib.Conference.ListConferencesResponse other = (com.fudan.ast.grpc.lib.Conference.ListConferencesResponse) obj;

    boolean result = true;
    result = result && getConferencesList()
        .equals(other.getConferencesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getConferencesCount() > 0) {
      hash = (37 * hash) + CONFERENCES_FIELD_NUMBER;
      hash = (53 * hash) + getConferencesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fudan.ast.grpc.lib.Conference.ListConferencesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code conference.ListConferencesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:conference.ListConferencesResponse)
      com.fudan.ast.grpc.lib.Conference.ListConferencesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fudan.ast.grpc.lib.Conference.ConferenceProto.internal_static_conference_ListConferencesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fudan.ast.grpc.lib.Conference.ConferenceProto.internal_static_conference_ListConferencesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fudan.ast.grpc.lib.Conference.ListConferencesResponse.class, com.fudan.ast.grpc.lib.Conference.ListConferencesResponse.Builder.class);
    }

    // Construct using com.fudan.ast.grpc.lib.Conference.ListConferencesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConferencesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (conferencesBuilder_ == null) {
        conferences_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        conferencesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fudan.ast.grpc.lib.Conference.ConferenceProto.internal_static_conference_ListConferencesResponse_descriptor;
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.Conference.ListConferencesResponse getDefaultInstanceForType() {
      return com.fudan.ast.grpc.lib.Conference.ListConferencesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.Conference.ListConferencesResponse build() {
      com.fudan.ast.grpc.lib.Conference.ListConferencesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fudan.ast.grpc.lib.Conference.ListConferencesResponse buildPartial() {
      com.fudan.ast.grpc.lib.Conference.ListConferencesResponse result = new com.fudan.ast.grpc.lib.Conference.ListConferencesResponse(this);
      int from_bitField0_ = bitField0_;
      if (conferencesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          conferences_ = java.util.Collections.unmodifiableList(conferences_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.conferences_ = conferences_;
      } else {
        result.conferences_ = conferencesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fudan.ast.grpc.lib.Conference.ListConferencesResponse) {
        return mergeFrom((com.fudan.ast.grpc.lib.Conference.ListConferencesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fudan.ast.grpc.lib.Conference.ListConferencesResponse other) {
      if (other == com.fudan.ast.grpc.lib.Conference.ListConferencesResponse.getDefaultInstance()) return this;
      if (conferencesBuilder_ == null) {
        if (!other.conferences_.isEmpty()) {
          if (conferences_.isEmpty()) {
            conferences_ = other.conferences_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureConferencesIsMutable();
            conferences_.addAll(other.conferences_);
          }
          onChanged();
        }
      } else {
        if (!other.conferences_.isEmpty()) {
          if (conferencesBuilder_.isEmpty()) {
            conferencesBuilder_.dispose();
            conferencesBuilder_ = null;
            conferences_ = other.conferences_;
            bitField0_ = (bitField0_ & ~0x00000001);
            conferencesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getConferencesFieldBuilder() : null;
          } else {
            conferencesBuilder_.addAllMessages(other.conferences_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fudan.ast.grpc.lib.Conference.ListConferencesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fudan.ast.grpc.lib.Conference.ListConferencesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.fudan.ast.grpc.lib.Conference.Conference> conferences_ =
      java.util.Collections.emptyList();
    private void ensureConferencesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        conferences_ = new java.util.ArrayList<com.fudan.ast.grpc.lib.Conference.Conference>(conferences_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fudan.ast.grpc.lib.Conference.Conference, com.fudan.ast.grpc.lib.Conference.Conference.Builder, com.fudan.ast.grpc.lib.Conference.ConferenceOrBuilder> conferencesBuilder_;

    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public java.util.List<com.fudan.ast.grpc.lib.Conference.Conference> getConferencesList() {
      if (conferencesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(conferences_);
      } else {
        return conferencesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public int getConferencesCount() {
      if (conferencesBuilder_ == null) {
        return conferences_.size();
      } else {
        return conferencesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public com.fudan.ast.grpc.lib.Conference.Conference getConferences(int index) {
      if (conferencesBuilder_ == null) {
        return conferences_.get(index);
      } else {
        return conferencesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder setConferences(
        int index, com.fudan.ast.grpc.lib.Conference.Conference value) {
      if (conferencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConferencesIsMutable();
        conferences_.set(index, value);
        onChanged();
      } else {
        conferencesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder setConferences(
        int index, com.fudan.ast.grpc.lib.Conference.Conference.Builder builderForValue) {
      if (conferencesBuilder_ == null) {
        ensureConferencesIsMutable();
        conferences_.set(index, builderForValue.build());
        onChanged();
      } else {
        conferencesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder addConferences(com.fudan.ast.grpc.lib.Conference.Conference value) {
      if (conferencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConferencesIsMutable();
        conferences_.add(value);
        onChanged();
      } else {
        conferencesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder addConferences(
        int index, com.fudan.ast.grpc.lib.Conference.Conference value) {
      if (conferencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConferencesIsMutable();
        conferences_.add(index, value);
        onChanged();
      } else {
        conferencesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder addConferences(
        com.fudan.ast.grpc.lib.Conference.Conference.Builder builderForValue) {
      if (conferencesBuilder_ == null) {
        ensureConferencesIsMutable();
        conferences_.add(builderForValue.build());
        onChanged();
      } else {
        conferencesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder addConferences(
        int index, com.fudan.ast.grpc.lib.Conference.Conference.Builder builderForValue) {
      if (conferencesBuilder_ == null) {
        ensureConferencesIsMutable();
        conferences_.add(index, builderForValue.build());
        onChanged();
      } else {
        conferencesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder addAllConferences(
        java.lang.Iterable<? extends com.fudan.ast.grpc.lib.Conference.Conference> values) {
      if (conferencesBuilder_ == null) {
        ensureConferencesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, conferences_);
        onChanged();
      } else {
        conferencesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder clearConferences() {
      if (conferencesBuilder_ == null) {
        conferences_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        conferencesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public Builder removeConferences(int index) {
      if (conferencesBuilder_ == null) {
        ensureConferencesIsMutable();
        conferences_.remove(index);
        onChanged();
      } else {
        conferencesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public com.fudan.ast.grpc.lib.Conference.Conference.Builder getConferencesBuilder(
        int index) {
      return getConferencesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public com.fudan.ast.grpc.lib.Conference.ConferenceOrBuilder getConferencesOrBuilder(
        int index) {
      if (conferencesBuilder_ == null) {
        return conferences_.get(index);  } else {
        return conferencesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public java.util.List<? extends com.fudan.ast.grpc.lib.Conference.ConferenceOrBuilder> 
         getConferencesOrBuilderList() {
      if (conferencesBuilder_ != null) {
        return conferencesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(conferences_);
      }
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public com.fudan.ast.grpc.lib.Conference.Conference.Builder addConferencesBuilder() {
      return getConferencesFieldBuilder().addBuilder(
          com.fudan.ast.grpc.lib.Conference.Conference.getDefaultInstance());
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public com.fudan.ast.grpc.lib.Conference.Conference.Builder addConferencesBuilder(
        int index) {
      return getConferencesFieldBuilder().addBuilder(
          index, com.fudan.ast.grpc.lib.Conference.Conference.getDefaultInstance());
    }
    /**
     * <code>repeated .conference.Conference conferences = 1;</code>
     */
    public java.util.List<com.fudan.ast.grpc.lib.Conference.Conference.Builder> 
         getConferencesBuilderList() {
      return getConferencesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fudan.ast.grpc.lib.Conference.Conference, com.fudan.ast.grpc.lib.Conference.Conference.Builder, com.fudan.ast.grpc.lib.Conference.ConferenceOrBuilder> 
        getConferencesFieldBuilder() {
      if (conferencesBuilder_ == null) {
        conferencesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.fudan.ast.grpc.lib.Conference.Conference, com.fudan.ast.grpc.lib.Conference.Conference.Builder, com.fudan.ast.grpc.lib.Conference.ConferenceOrBuilder>(
                conferences_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        conferences_ = null;
      }
      return conferencesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:conference.ListConferencesResponse)
  }

  // @@protoc_insertion_point(class_scope:conference.ListConferencesResponse)
  private static final com.fudan.ast.grpc.lib.Conference.ListConferencesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fudan.ast.grpc.lib.Conference.ListConferencesResponse();
  }

  public static com.fudan.ast.grpc.lib.Conference.ListConferencesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListConferencesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListConferencesResponse>() {
    @java.lang.Override
    public ListConferencesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListConferencesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListConferencesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListConferencesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fudan.ast.grpc.lib.Conference.ListConferencesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

