// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conference.proto

package com.fudan.ast.grpc.lib.Conference;

public interface StartSubmissionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conference.StartSubmissionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 conference_id = 1;</code>
   */
  int getConferenceId();
}
