// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conference.proto

package com.fudan.ast.grpc.lib.Conference;

public interface UpdateConferenceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conference.UpdateConferenceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string short_name = 2;</code>
   */
  java.lang.String getShortName();
  /**
   * <code>string short_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getShortNameBytes();

  /**
   * <code>string full_name = 3;</code>
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>.google.protobuf.Timestamp start_date = 4;</code>
   */
  boolean hasStartDate();
  /**
   * <code>.google.protobuf.Timestamp start_date = 4;</code>
   */
  com.google.protobuf.Timestamp getStartDate();
  /**
   * <code>.google.protobuf.Timestamp start_date = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp end_date = 5;</code>
   */
  boolean hasEndDate();
  /**
   * <code>.google.protobuf.Timestamp end_date = 5;</code>
   */
  com.google.protobuf.Timestamp getEndDate();
  /**
   * <code>.google.protobuf.Timestamp end_date = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder();

  /**
   * <code>string location = 6;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 6;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>.google.protobuf.Timestamp submission_start_date = 7;</code>
   */
  boolean hasSubmissionStartDate();
  /**
   * <code>.google.protobuf.Timestamp submission_start_date = 7;</code>
   */
  com.google.protobuf.Timestamp getSubmissionStartDate();
  /**
   * <code>.google.protobuf.Timestamp submission_start_date = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSubmissionStartDateOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp submission_end_date = 8;</code>
   */
  boolean hasSubmissionEndDate();
  /**
   * <code>.google.protobuf.Timestamp submission_end_date = 8;</code>
   */
  com.google.protobuf.Timestamp getSubmissionEndDate();
  /**
   * <code>.google.protobuf.Timestamp submission_end_date = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSubmissionEndDateOrBuilder();

  /**
   * <code>.conference.ConferenceStatus status = 9;</code>
   */
  int getStatusValue();
  /**
   * <code>.conference.ConferenceStatus status = 9;</code>
   */
  com.fudan.ast.grpc.lib.Conference.ConferenceStatus getStatus();
}
