// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.fudan.ast.grpc.lib;

public final class AuthProto {
  private AuthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JwtRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JwtRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JwtToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JwtToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JwtTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JwtTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegisterUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegisterUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidateEmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidateEmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidateEmailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidateEmailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\"-\n\nJwtRequest\022\r\n\005email\030\001 \001(" +
      "\t\022\020\n\010password\030\002 \001(\t\"\034\n\010JwtToken\022\020\n\010jwtTo" +
      "ken\030\001 \001(\t\"3\n\020JwtTokenResponse\022\020\n\010jwtToke" +
      "n\030\001 \001(\t\022\r\n\005valid\030\002 \001(\010\"7\n\020ValidateRespon" +
      "se\022\r\n\005valid\030\001 \001(\010\022\024\n\004role\030\002 \001(\0162\006.Roles\"" +
      "o\n\023RegisterUserRequest\022\020\n\010username\030\001 \001(\t" +
      "\022\020\n\010password\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\023\n\013aff" +
      "iliation\030\004 \001(\t\022\020\n\010location\030\005 \001(\t\"B\n\024Regi" +
      "sterUserResponse\022\n\n\002id\030\001 \001(\005\022\r\n\005state\030\002 " +
      "\001(\010\022\017\n\007message\030\003 \001(\t\"%\n\024ValidateEmailReq" +
      "uest\022\r\n\005email\030\001 \001(\t\"&\n\025ValidateEmailResp" +
      "onse\022\r\n\005valid\030\001 \001(\010*&\n\005Roles\022\r\n\tROLE_USE" +
      "R\020\000\022\016\n\nROLE_ADMIN\020\0012o\n\013AuthService\0224\n\020ge" +
      "nerateJwtToken\022\013.JwtRequest\032\021.JwtTokenRe" +
      "sponse\"\000\022*\n\010validate\022\t.JwtToken\032\021.Valida" +
      "teResponse\"\0002\216\001\n\017RegisterService\022;\n\014regi" +
      "sterUser\022\024.RegisterUserRequest\032\025.Registe" +
      "rUserResponse\022>\n\rvalidateEmail\022\025.Validat" +
      "eEmailRequest\032\026.ValidateEmailResponseB%\n" +
      "\026com.fudan.ast.grpc.libB\tAuthProtoP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JwtRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JwtRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JwtRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_JwtToken_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JwtToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JwtToken_descriptor,
        new java.lang.String[] { "JwtToken", });
    internal_static_JwtTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_JwtTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JwtTokenResponse_descriptor,
        new java.lang.String[] { "JwtToken", "Valid", });
    internal_static_ValidateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ValidateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidateResponse_descriptor,
        new java.lang.String[] { "Valid", "Role", });
    internal_static_RegisterUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RegisterUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterUserRequest_descriptor,
        new java.lang.String[] { "Username", "Password", "Email", "Affiliation", "Location", });
    internal_static_RegisterUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RegisterUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegisterUserResponse_descriptor,
        new java.lang.String[] { "Id", "State", "Message", });
    internal_static_ValidateEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ValidateEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidateEmailRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_ValidateEmailResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ValidateEmailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidateEmailResponse_descriptor,
        new java.lang.String[] { "Valid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
