// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.fudan.ast.grpc.lib;

public interface RegisterUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegisterUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string affiliation = 4;</code>
   */
  java.lang.String getAffiliation();
  /**
   * <code>string affiliation = 4;</code>
   */
  com.google.protobuf.ByteString
      getAffiliationBytes();

  /**
   * <code>string location = 5;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 5;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
