// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.fudan.ast.grpc.lib;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string affiliation = 3;</code>
   */
  java.lang.String getAffiliation();
  /**
   * <code>string affiliation = 3;</code>
   */
  com.google.protobuf.ByteString
      getAffiliationBytes();

  /**
   * <code>string location = 4;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 4;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
