// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.fudan.ast.grpc.lib;

public interface ValidateEmailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ValidateEmailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
