// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.fudan.ast.grpc.lib;

public interface ValidateEmailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ValidateEmailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   */
  boolean getValid();
}
