server:
  port: 8081
grpc:
  client:
    grpc-auth-server:
      address: 'discovery:///grpc-auth-server'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    grpc-user-server:
      address: 'discovery:///grpc-user-server'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  application:
    name: grpc-user-controller
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${cloudServerSlave1:localhost}:8781/eureka/,http://${cloudServerSlave2:localhost}:8782/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator info
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8
    name:grpc-user-controller
